# main.py
import os
from dotenv import load_dotenv
from workflow.graph import build_research_graph
from workflow.state import create_initial_state

load_dotenv()

def main():
    # Ensure API Key is set
    if not os.getenv("DASHSCOPE_API_KEY"):
        print("❌ 请先设置 DASHSCOPE_API_KEY 环境变量！")
        return

    # 1. Obtain the compiled agent team (App)
    research_app = build_research_graph()

    # 2. Define initial input
    # This is the user's original request; the graph engine will automatically convert it to ResearchState format.
    initial_input = create_initial_state("who is adam?")


    # 🔴 Key modification: Assign a unique "thread ID" for this task
    # If the code is interrupted, the next run will continue from the breakpoint as long as the same thread_id is used!
    config = {"configurable": {"thread_id": "research_task_001"}}

    print("\n" + "=" * 50)
    print("🚀 启动 DeepScholar 自动化科研引擎")
    print("=" * 50)

    # 3. One-click start! (invoke will automatically follow the graph from start to finish)
    final_state = research_app.invoke(initial_input,config=config)

    print("\n" + "=" * 50)
    print("🎉 全流程执行完毕！最终生成的学术综述草稿如下：")
    print("=" * 50)

    # Directly print the draft generated by the Writer, instead of loop-printing extracted_insights
    if "draft" in final_state and final_state["draft"]:
        print(final_state["draft"])
    else:
        print("⚠️ 未能生成有效草稿。")


if __name__ == "__main__":
    main()
